name: 'Update pictos on clients'
description: 'update yarn pictos dependence'
runs:
  using: "composite"
  steps: 
    - run: yarn upgrade pictos --latest && yarn build
      working-directory: /var/www/pictos/qa/pictos-admin-client/
      shell: bash
    - run: yarn upgrade pictos --latest && yarn build
      working-directory: /var/www/pictos/qa/pictos-web-app/
      shell: bash