name: 'Update pictos on clients'
description: 'update yarn pictos dependence'
runs:
  using: "composite"
  steps: 
    - run: npm install pictos@latest && npm run build
      working-directory: /var/www/pictos/pictos-admin-client/
      shell: bash
    - run: npm install pictos@latest && npm run build
      working-directory: /var/www/pictos/pictos-web-app/
      shell: bash