name: 'Update pictos on clients'
description: 'update yarn pictos dependence'
runs:
  using: "composite"
  steps: 
    - run: yarn add https://github.com/accesibilidad-inclusion/pictogramas.git#master && yarn build
      working-directory: /var/www/pictos/pictos-admin-client/
      shell: bash
    - run: yarn add https://github.com/accesibilidad-inclusion/pictogramas.git#master && yarn build
      working-directory: /var/www/pictos/pictos-web-app/
      shell: bash