name: 'Update pictos DB'
description: 'excecute sync script'
runs:
  using: "composite"
  steps: 
    - run: node script.js
      working-directory: /var/www/production/pictos-backend/
      shell: bash