on:
  push:
    branches:
      - ci_testing

jobs:
  ci_update_repo_job:
    runs-on: self-hosted
    name: Ci update repository on clients
    steps:
    - uses: accesibilidad-inclusion/pictogramas/actions/action_clients
  ci_update_db_job:
    runs-on: self-hosted
    name: Ci update database
    needs: ci_update_repo_job
    steps:
    - uses: accesibilidad-inclusion/pictogramas/actions/actions/action_db