on:
  push:
    branches:
      - qa

jobs:
  ci_update_repo_job:
    runs-on: self-hosted
    name: Ci update repository on clients
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: ./.github/actions/action-clients-qa
  ci_update_db_job:
    runs-on: self-hosted
    name: Ci update database
    needs: ci_update_repo_job
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: ./.github/actions/action-db-qa
    